---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: test-route
    namespace: homelab
spec:
    entryPoints:
        - web
    routes:
        - kind: Rule
          match: PathPrefix(`/`)
          services:
              - name: hello
                port: 80
